name: curlstat
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - transformers
  - curlhs
  - aeson
  - servant-server
  - warp
  - wai-middleware-throttle
  - clock

executables:
  curlstat-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
